// The bdslw60 word labels are Banglish transliterations (e.g. "baba", "cha"). Map them to
// proper Bangla for display and for the Gemini sentence builder. Unmapped words fall back
// to the original string. Covers all 60 classes of the trained word model.

const MAP: Record<string, string> = {
  aam: "আম",
  aaple: "আপেল",
  ac: "এসি",
  aids: "এইডস",
  alu: "আলু",
  anaros: "আনারস",
  angur: "আঙুর",
  apartment: "অ্যাপার্টমেন্ট",
  attio: "আত্মীয়",
  "audio cassette": "অডিও ক্যাসেট",
  ayna: "আয়না",
  baandej: "ব্যান্ডেজ",
  baat: "ভাত",
  baba: "বাবা",
  balti: "বালতি",
  balu: "বালু",
  bhai: "ভাই",
  biscuts: "বিস্কুট",
  bon: "বোন",
  boroi: "বরই",
  bottam: "বোতাম",
  bou: "বউ",
  cake: "কেক",
  capsule: "ক্যাপসুল",
  cha: "চা",
  chacha: "চাচা",
  chachi: "চাচি",
  chadar: "চাদর",
  chal: "চাল",
  chikissha: "চিকিৎসা",
  chini: "চিনি",
  chips: "চিপস",
  chiruni: "চিরুনি",
  chocolate: "চকলেট",
  "chokh utha": "চোখ ওঠা",
  chosma: "চশমা",
  churi: "চুড়ি",
  clip: "ক্লিপ",
  cream: "ক্রিম",
  dada: "দাদা",
  dadi: "দাদি",
  daeitto: "দায়িত্ব",
  dal: "ডাল",
  debor: "দেবর",
  denadar: "দেনাদার",
  dengue: "ডেঙ্গু",
  doctor: "ডাক্তার",
  dongson: "দংশন",
  dulavai: "দুলাভাই",
  durbol: "দুর্বল",
  jomoj: "যমজ",
  juta: "জুতা",
  konna: "কন্যা",
  maa: "মা",
  tattha: "তথ্য",
  toothpaste: "টুথপেস্ট",
  tshirt: "টি-শার্ট",
  tubelight: "টিউবলাইট",
  tupi: "টুপি",
  tv: "টিভি",
};

export function toBn(word: string): string {
  return MAP[word.toLowerCase().trim()] || word;
}
